### PR TITLE
updated with tabs, padding to faq, menuIcon and close button

### LINKED ISSUE #33: Add tabs and styling to the sidebar and padding to FAQ
Add tabs to the links in the sidebar and add left padding to the FAQ

### PR DESCRIPTION
**Pull request by SutarPrasad**
* **Describe the changes implemented in this PR** (Bug fix, feature, docs update, ...)
In this PR I have added the tabs inside the sidebar, padding to faq content MenuIcon and close button for reduced screen size mode and styling to it. These changes cover the review mentioned in #30 

* **Please check if the PR fulfils these requirements**

- [x] Closes #33  ("Replace xxxx with the Github issue number")
- [x] ESLINT passed

### CODE REVIEW

**Comment by gareth-j** [comment]
Just a few higher level suggestions for this:
- the selection and clear button/dropdown should be below the plot
- I don't think we need the shadowing around the items, and definitely not the map, I think that looks out of place
- for me the burger menu has a surrounding line on a narrow window

**Comment by SutarPrasad** [comment]
I will check the burger menu for the small screen, it did not pop up for me. I will change the configurations and hunt for it to be resolved.
I would stick to the species and clear at the top because it then generates a flow in users' minds going from top to bottom. It usually is left to right from top to bottom.

**Comment by SutarPrasad** [comment]
@gareth-j I am trying to have a card-based styling to the dashboard, However, to do so it will take some more time hence the shadowing is the closest form of mimicking card-based structure. Dashboards implement a card-based structure to avoid components being as plain as some kind of webpage.

**Comment by gareth-j** [comment]
I don't think we need these changes at the moment. Thanks for looking at this but I think the previous interface was cleaner.

**Comment by SutarPrasad** [comment]
I checked with Matt on this and he seemed to be happy with the new interface. Hence I would like to go ahead with this and will rework on it if we get any such suggestions.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SutarPrasad** [comment]
not required as per team discussion

**Pull request closed without merging**
